'''
Script for reading in config.ini that is generated by generate_config.py
'''
from configparser import ConfigParser
from Models import Register


#Read config.ini file
config_object = ConfigParser()
config_object.read("config.ini")

# Grab device 1`
device_1 = dict(config_object["DEVICE_1"])
print(device_1[3])
